### PR TITLE
fix: Council Pack 14

### PR DESCRIPTION
**Pull request by m26dvd**
fix: #984
fix: #982 
fix: #980 
fix: #776
fix: #969 
fix: #695

### CODE REVIEW

**Review by robbrad — APPROVED** [review]

**Comment by dp247** [comment]
I love these packs, it's like getting DLC for your favorite game

**Comment by m26dvd** [comment]
@robbrad @dp247 Running through some more currently so will add a few more commits before marking the PR as ready :-D

**Comment by blaired** [comment]
> I love these packs, it's like getting DLC for your favorite game

And Christmas, paitently waiting for my local authority to be added :-)

**Comment by m26dvd** [comment]
> > I love these packs, it's like getting DLC for your favorite game
> 
> And Christmas, paitently waiting for my local authority to be added :-)

@blaired Is there an open request for your local authority? Feel free to reach out and let me know which one and I'll take a look at it :-)

**Comment by blaired** [comment]
> > > I love these packs, it's like getting DLC for your favorite game
> > 
> > 
> > And Christmas, paitently waiting for my local authority to be added :-)
> 
> @blaired Is there an open request for your local authority? Feel free to reach out and let me know which one and I'll take a look at it :-)

Yes, there are two #868 and #919.  There was some confusion on one of the request as to the name of the LA and I'm not sure myself after checking but I think barbergh and mid-suffolk are separate districts.  The waste collections are different and have their own pages.

https://www.babergh.gov.uk/w/check-your-collection-day

**Comment by captain-ted** [comment]
> > > > I love these packs, it's like getting DLC for your favorite game
> > > 
> > > 
> > > And Christmas, paitently waiting for my local authority to be added :-)
> > 
> > 
> > @blaired Is there an open request for your local authority? Feel free to reach out and let me know which one and I'll take a look at it :-)
> 
> Yes, there are two #868 and #919. There was some confusion on one of the request as to the name of the LA and I'm not sure myself after checking but I think barbergh and mid-suffolk are separate districts. The waste collections are different and have their own pages.
> 
> https://www.babergh.gov.uk/w/check-your-collection-day

Yeah I think I instigated the confusion. I think they are separate… but oddly very close 🤷‍♂️. I’m oddly excited for Babergh to be added so that I can start to make enough ‘benefits’ to convince my wife that an in home smart display is needed 😅

**Comment by m26dvd** [comment]
@blaired @captain-ted Both will be included in Council Pack 15 over at #992 :-) Happy Christmas :-P

**Comment by captain-ted** [comment]
> @blaired @captain-ted Both will be included in Council Pack 15 over at #992 :-) Happy Christmas :-P

amazing! 🎅🎄

**Comment by blaired** [comment]
> > > > > I love these packs, it's like getting DLC for your favorite game
> 
> > > > 
> 
> > > > 
> 
> > > > And Christmas, paitently waiting for my local authority to be added :-)
> 
> > > 
> 
> > > 
> 
> > > @blaired Is there an open request for your local authority? Feel free to reach out and let me know which one and I'll take a look at it :-)
> 
> > 
> 
> > Yes, there are two #868 and #919. There was some confusion on one of the request as to the name of the LA and I'm not sure myself after checking but I think barbergh and mid-suffolk are separate districts. The waste collections are different and have their own pages.
> 
> > 
> 
> > https://www.babergh.gov.uk/w/check-your-collection-day
> 
> 
> 
> Yeah I think I instigated the confusion. I think they are separate… but oddly very close 🤷‍♂️. I’m oddly excited for Babergh to be added so that I can start to make enough ‘benefits’ to convince my wife that an in home smart display is needed 😅

@captain-ted what smart display are you looking. Not sure if there is an option to PM me to avoid filling up this thread.

**Comment by blaired** [comment]
> @blaired @captain-ted Both will be included in Council Pack 15 over at #992 :-) Happy Christmas :-P
> 
> 

Awesome, thank you. I'll leave a mince pie out for you. Do the council packs get included in updates to the integration in HACS?

**Comment by dp247** [comment]
> Awesome, thank you. I'll leave a mince pie out for you. Do the council packs get included in updates to the integration in HACS?

All changes are added to HACS automatically, you just need to update the plugin version 👀

**Comment by captain-ted** [comment]
> > > > > > I love these packs, it's like getting DLC for your favorite game
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > And Christmas, paitently waiting for my local authority to be added :-)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > @blaired Is there an open request for your local authority? Feel free to reach out and let me know which one and I'll take a look at it :-)
> > 
> > 
> > > 
> > 
> > 
> > > Yes, there are two #868 and #919. There was some confusion on one of the request as to the name of the LA and I'm not sure myself after checking but I think barbergh and mid-suffolk are separate districts. The waste collections are different and have their own pages.
> > 
> > 
> > > 
> > 
> > 
> > > https://www.babergh.gov.uk/w/check-your-collection-day
> > 
> > 
> > Yeah I think I instigated the confusion. I think they are separate… but oddly very close 🤷‍♂️. I’m oddly excited for Babergh to be added so that I can start to make enough ‘benefits’ to convince my wife that an in home smart display is needed 😅
> 
> @captain-ted what smart display are you looking at? Not sure if there is an option to PM me to avoid filling up this thread.

Couldn’t see an option of PMing - short answer - I don’t know yet. Might end up using a Mac mini with a separate touchscreen display because what I need is to have a dashboard containing a HK section for my HKSV cameras and then a larger HA section. Not sure how I could get a HK view on a non-Apple device.

Im very very new to the HA world though and am not well versed in code etc so I’m sure it’ll be a long job with much research needed!

**Comment by captain-ted** [comment]
Hi, have got this working for Babergh for recycling (blue bin) and household waste (black bin).

Is it possible to also get this working for the garden waste (brown bin)?

**Comment by m26dvd** [comment]
@captain-ted Garden Waste will be added in the next update

**Comment by captain-ted** [comment]
> @captain-ted Garden Waste will be added in the next update

Amazing! Thank you so much. Working a treat!

**Pull request merged**
