### PR TITLE
Add Gloucester city council driver

### LINKED ISSUE #565: Gloucester City Council
### Name of Council

Gloucester City Council 

### Example Address/Postcode

73 Quayside Way, Hempsted, Gloucester, GL2 5EX

### Additional Information

Link is https://gloucester-self.achieveservice.com/en/service/Bins___Check_your_bin_day

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

### PR DESCRIPTION
**Pull request by simoncozens**
Fixes #565.

```
$ PYTHONPATH=. python3 uk_bin_collection/uk_bin_collection/collect_data.py GloucesterCityCouncil https://gloucester-self.achieveservice.com/en/service/Bins___Check_your_bin_day -p "GL2 5EX" -n 73 -u 10007315012
{
    "bins": [
        {
            "type": "Household waste (black bin)",
            "collectionDate": "13/09/2024"
        },
        {
            "type": "Household recycling (green box, brown food bin and blue sack)",
            "collectionDate": "13/09/2024"
        }
    ]
}
```

### CODE REVIEW

**Comment by robbrad** [comment]
@simoncozens : https://github.com/robbrad/UKBinCollectionData/actions/runs/10775106025/job/29878905553

Looks like it's failing for our test address in the tests/input.json file

**Comment by simoncozens** [comment]
Gah. I've been testing with local browser, not Selenium. It will probably take me a while to get around to setting up docker and all the other gubbins. If you want to take over the PR, please feel free.

**Comment by robbrad** [comment]
We have a dev container that includes selenium as a setup etc https://github.com/robbrad/UKBinCollectionData/tree/master/.devcontainer

You can use VSCode with this

**Comment by robbrad** [comment]
@simoncozens Just tested this on the devcontainer and it worked fine - ill merge now

**Comment by gjpgjp** [comment]
Does this need a selenium server to work, there is no option in the configuration for Gloucester City Council to specify a server URL

**Comment by robbrad** [comment]
> Does this need a selenium server to work, there is no option in the configuration for Gloucester City Council to specify a server URL

Ah that needs adding to the input.json in the code

@simoncozens are you able to add that line? If not I can.

Just have a look at another council and copy it exactly the same. That's how the custom component knows it's selenium

**Pull request merged**
