### PR TITLE
Add support for South Tyneside Council

### LINKED ISSUE #4: South Tyneside Council
Please could South Tyneside be added?

https://www.southtyneside.gov.uk/article/33352/Bin-collection-dates

Example post code: NE33 3LH

### PR DESCRIPTION
**Pull request by dp247**
This closes #4.

Special thanks to @ZackaryH8 for the Postman API making it a thousand times easier!

@robbrad I've added the items mentioned in #79 - could you check that it's all good please? 😀

### CODE REVIEW

**Comment by ZackaryH8** [comment]
You're welcome, I do plan on adding some more in the future to help people wishing to add their council to the repository. :)

**Comment by dp247** [comment]
> You're welcome, I do plan on adding some more in the future to help people wishing to add their council to the repository. :)

If you can translate the JWT token auth, feel free to add my one for Cardiff City Council :)

**Comment by ZackaryH8** [comment]
> If you can translate the JWT token auth, feel free to add my one for Cardiff City Council :)

I will take a look when I get the chance.

**Comment by dp247** [comment]
Don't include https://github.com/robbrad/UKBinCollectionData/pull/82/commits/8f48dfb51704879932873f64e21ad43bf9b9be34 or https://github.com/robbrad/UKBinCollectionData/pull/82/commits/1016e466d4a63a849cdce83b7db0cc297af8cfa1... I updated the python version thinking it would make the action work. It turns out it doesn't work like that (who knew, not me lol)

**Review by robbrad — COMMENTED** [review]
Nice Work - but you need a JSON Schema file for the feature to pass @dp247 

Take the output JSON - head over to https://jsonformatter.org/json-to-jsonschema make a schema (not saying its optimum - but it works for now)

The pipeline then validates the output (as dates and type change etc ) against the schema at the time of the pipeline run - so when the pipeline runs its doing an actual pull of data from the council :)

**Comment by robbrad** [comment]
https://github.com/robbrad/UKBinCollectionData/tree/master/uk_bin_collection/tests/council_schemas

**Comment by dp247** [comment]
Ah, knew I was missing something! Thanks for the explanation!

**Comment by robbrad** [comment]
> Ah, knew I was missing something! Thanks for the explanation!

I really need to document it TBH - basically one page for integration tests and one for unit-tests

**Pull request merged**
