### PR TITLE
feat: Add BefordshireCouncil scraper

### PR DESCRIPTION
**Pull request by simondrake**

### CODE REVIEW

**Comment by dp247** [comment]
Closes #387

**Review by robbrad — APPROVED** [review]

**Comment by simondrake** [comment]
@robbrad @dp247 - is this supposed to get automatically pushed to HACS? The new council isn't showing and HACS shows it was last updated 21 hours ago (presumably https://github.com/robbrad/UKBinCollectionData/pull/471?).

**Comment by simondrake** [comment]
:thinking: @robbrad @dp247 - I was expected to see an option to add `postcode` and uprn` when adding the new council, but there's nothing. Did I miss something?

image

**Comment by simondrake** [comment]
This is what I see for Bury

image

**Comment by simondrake** [comment]
Looks like it wasn't added to https://github.com/robbrad/UKBinCollectionData/blob/master/wiki/Councils.md, which may well be the problem :thinking:

**Comment by simondrake** [comment]
I'm assuming it's because I missed a couple things from the `input.json` file - https://github.com/robbrad/UKBinCollectionData/pull/473

**Pull request merged**
