### PR TITLE
fix: Handle Barnet council cookies message

### PR DESCRIPTION
**Pull request by OliverCullimore**
Fix accepting cookies before entering postcode

### CODE REVIEW

**Comment by OliverCullimore** [comment]
@robbrad also failing on this one where I've only added a few lines which is odd

**Comment by OliverCullimore** [comment]
Council tests failing with a "The currently activated Python version 3.10.12 is not supported by the project (>=3.11)." error.

Unable to see a reason for this error as behave.yml is using 3.11 and 3.12 now.

**Comment by OliverCullimore** [comment]
@robbrad  Looks like it was present in another recent PR too https://github.com/robbrad/UKBinCollectionData/actions/runs/9138162537/job/25128988718#step:9:14 but either now we've removed the line caching poetry or due to upping the min python version it's escalated it from a warning to an error.

**Comment by robbrad** [comment]
> We've also dropped from 152 test cases to 44 https://robbrad.github.io/UKBinCollectionData/3.12/

Thats because it only tests the councils that changed :)

**Review by robbrad — APPROVED** [review]

**Pull request merged**
