### PR TITLE
Fix Lint Errors

### PR DESCRIPTION
**Pull request by zoenolan**

### CODE REVIEW

**Comment by dp247** [comment]
Paging @robbrad for this - I don't lint personally so not sure these changes affect too much

**Comment by zoenolan** [comment]
to add some detail. these are the `make pycodestyle` run before and after the changes

**Before**
- 4       E128 continuation line under-indented for visual indent
- 2       E203 whitespace before ':'
- 1       E231 missing whitespace after ','
- 1       E265 block comment should start with '# '
- 4       E275 missing whitespace after keyword
- 14      E302 expected 2 blank lines, found 1
- 1       E303 too many blank lines (3)
- 1       E402 module level import not at top of file
- 568     E501 line too long (84 > 79 characters)
- 3       W291 trailing whitespace
- 1       W292 no newline at end of file
- 7       W293 blank line contains whitespace
- 2       W391 blank line at end of file
- 9       W605 invalid escape sequence '\d'

**After**
- 483     E501 line too long (84 > 79 characters)

**Comment by zoenolan** [comment]
and I just reran  `make integration-tests`. i get one more failure after the changes. I'll have a look at that

**Before**
- 8 warnings
- 19 failed
- 52 passed 


**After**
- 4 warnings
- 20 failed
- 51 passed

**Comment by zoenolan** [comment]
I resynced with the master and ran tests again. it seems to fine now

**Before** ([bad56cb31c693fbb25509181450f63327d66abee](https://github.com/robbrad/UKBinCollectionData/tree/bad56cb31c693fbb25509181450f63327d66abee))
- 21 failed, 53 passed, 9 warnings
- 21 failed, 53 passed, 4 warnings
- 21 failed, 53 passed, 4 warnings

**After**
- 21 failed, 53 passed, 4 warnings
- 21 failed, 53 passed, 4 warnings
- 21 failed, 53 passed, 4 warnings

**Review by robbrad — APPROVED** [review]

**Pull request merged**
