### PR TITLE
feat: Add Rhondda Cynon Taff

### LINKED ISSUE #357: Request to add Rhondda Cynon Taff
### Name of Council

Rhondda Cynon Taff

### Example Postcode

CF72 9JD

### Additional Information

https://www.rctcbc.gov.uk/EN/Resident/RecyclingandWaste/RecyclingandWasteCollectionDays.aspx - bin collection

https://www.rctcbc.gov.uk/EN/Contactus/OnlineServices.aspx - Generic services

Been trying to find any form of web API to pull services from but havent managed to find anything myself just yet.

### PR DESCRIPTION
**Pull request by dp247**
Hello, hello. It's me.

This closes #357 very nicely. Please let me know if I have broken anything... it has been a while hahaha.

### CODE REVIEW

**Review by robbrad — APPROVED** [review]

**Comment by robbrad** [comment]
Looks like some commit lint errors to fix @dp247 😅

**Comment by dp247** [comment]
> Looks like some commit lint errors to fix @dp247 😅

I can do that... once I figure out what that means 😅

**Comment by robbrad** [comment]
> > Looks like some commit lint errors to fix @dp247 😅
> 
> 
> 
> I can do that... once I figure out what that means 😅

Wish I knew too! Think @OliverCullimore added this nice bit of workflow

**Comment by robbrad** [comment]
Looks like a quality gate

**Comment by robbrad** [comment]
Try this PR  https://github.com/robbrad/UKBinCollectionData/issues/350

Which was green

**Comment by dp247** [comment]
> Try this PR #350
> 
> Which was green

I thought it might be the `feat: ` bit, but no dice

**Comment by OliverCullimore** [comment]
@robbrad @dp247 it's checking the commit message e.g. on #350 as @robbrad referenced the commit message contains a prefix of `feat:`

image

So essentially going forwards each commit should now have a prefix denoting it's type

The main prefixes I expect us to use are:

`feat:` and `fix:` for anything council-related
`ci:` for workflows
`docs:` for wiki/readme/contributing changes

This then enables https://commitizen-tools.github.io/commitizen/ to automatically bump the version for us based on our commit messages

Hope that all makes sense?

---

So @dp247 for your commits on this one they should've been prefixed with `feat:` as you're adding support for a new council e.g. "feat: Add supporting files for Rhondda Cynon Taff Council"

I'm not sure if we can edit commit messages to fix this? Otherwise it won't harm to merge this, it just won't generate a new version therefore won't be released and able to be used until another PR is merged that does trigger a release.

**Comment by OliverCullimore** [comment]
@dp247 I've re-committed your support files commit with a feat: prefix so hopefully the PR should trigger a new version at least now

**Comment by robbrad** [comment]
Thanks @OliverCullimore this makes total sense. Sorry had a lot on recently and not paid close attention.

Could the same commit checks check for the files we need eg input.json etc?

**Comment by dp247** [comment]
Thank you! That's a nifty thing - would it be worth adding something to Contributing.md as a reminder?

**Comment by OliverCullimore** [comment]
That seems to have done the trick so @dp247 that's your first changes release in the new way https://github.com/robbrad/UKBinCollectionData/releases/tag/0.13.0 😃 

@robbrad no worries at all, it's a bit of a change to how we were doing things and a learning curve for me on the existence and implementation of it all. But hopefully, now it's set up, it will enable us to focus what little time we have on adding more councils and improvements rather than manually creating releases now.

@dp247 your commits have usefully also highlighted I missed updating the wiki action's commit message so I'll try and add a PR to fix that now 😄 

And @robbrad I'm sure it should be possible to set something up to check for certain files but it would likely need some complex rules to handle adding a council vs fixing a small issue with an existing one, so maybe more something to revisit in the future?

**Comment by OliverCullimore** [comment]
> Thank you! That's a nifty thing - would it be worth adding something to Contributing.md as a reminder?

.... I did add a line https://github.com/robbrad/UKBinCollectionData/blob/master/CONTRIBUTING.md#make-sure-commit-messages-follow-the-conventional-commits-convention but I'm guessing it might need better placement and rewording as even I just found it hard to find where I'd put it in there

**Comment by robbrad** [comment]
> That seems to have done the trick so @dp247 that's your first changes release in the new way https://github.com/robbrad/UKBinCollectionData/releases/tag/0.13.0 😃 
> 
> 
> 
> @robbrad no worries at all, it's a bit of a change to how we were doing things and a learning curve for me on the existence and implementation of it all. But hopefully, now it's set up, it will enable us to focus what little time we have on adding more councils and improvements rather than manually creating releases now.
> 
> 
> 
> @dp247 your commits have usefully also highlighted I missed updating the wiki action's commit message so I'll try and add a PR to fix that now 😄 
> 
> 
> 
> And @robbrad I'm sure it should be possible to set something up to check for certain files but it would likely need some complex rules to handle adding a council vs fixing a small issue with an existing one, so maybe more something to revisit in the future?

Definitely parking lot.

This is awesome and I love that this project has supported a learning journey. It's a massive part of why I set it up all those years ago... to learn Python!!! 

Kudos team!!

**Pull request merged**
