### PR TITLE
Feature/#53 integration tests

### PR DESCRIPTION
**Pull request by robbrad**
https://github.com/robbrad/UKBinCollectionData/issues/53 #53 
https://github.com/robbrad/UKBinCollectionData/issues/56 #56 
https://github.com/robbrad/UKBinCollectionData/issues/60 #60 
https://github.com/robbrad/UKBinCollectionData/issues/64 #64

### CODE REVIEW

**Comment by dp247** [comment]
I'll get on this in the next few days 😁

**Comment by robbrad** [comment]
@dp247 - quite a few changes here

-Project restructure
-Use of Poetry (which rocks btw) - just do poetry install from the project root
-Intergration tests see [Link](https://github.com/robbrad/UKBinCollectionData/blob/feature/%2353_integration_tests/uk_bin_collection/tests/features/validate_council_outputs.feature )

Once merged we need to make a Json Schema for each council - for now this could just be generated but as a start [Cheshire East Schema](https://github.com/robbrad/UKBinCollectionData/pull/68/files#diff-3159020bbad0349c7323282f9100b0121861396d69104f93bfeef5e9a63dac6d)

**Comment by robbrad** [comment]
Behave launch.json for vscode

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true
        },
        {
            "name": "Behave: Current File",
            "type": "python",
            "request": "launch",
            "module": "behave",
            "args": ["uk_bin_collection/tests/features/${fileBasenameNoExtension}.feature"]
        },
        {
            "name": "Behave @testThis",
            "type": "python",
            "request": "launch",
            "module": "behave",
            "args": [
               "--tags= testThis",
               "--no-skipped"
            ]
        },
        {
            "name": "Behave Run ALL",
            "type": "python",
            "request": "launch",
            "module": "behave",
            "args": ["uk_bin_collection/tests/features/"]
        }
    ]
}`

**Comment by robbrad** [comment]
@dp247 - any chance you had a look at this yet mate?

**Comment by dp247** [comment]
> @dp247 - any chance you had a look at this yet mate?

It's my job for today, I snuck away for a few days 😆

**Review by dp247 — APPROVED** [review]
Looks good @robbrad!

I did have an issue with Poetry installing dependencies, but I'm willing to put that down to my environment rather than a project fault 😆

**Comment by robbrad** [comment]
> 

That's allowed ! 🥇

**Comment by robbrad** [comment]
> 

That's allowed ! 🥇

**Comment by robbrad** [comment]
@dp247 - what issue did you have? 

I think there is a way with poetry to have the .venv in project

**Comment by dp247** [comment]
It was an infinite loop when updating and installing from repositories. I've seen some issues for it floating about, so I'm sure it's more of a me-thing than a project-thing.

**Pull request merged**
