### PR TITLE
feat: #525 Adding API Server and Docker build

### LINKED ISSUE #525: API for this integration
based on the request here : https://github.com/robbrad/UKBinCollectionData/discussions/446

Create an api that can be hosted

### PR DESCRIPTION
**Pull request by robbrad**
closes #525

### CODE REVIEW

**Review by OliverCullimore — APPROVED** [review]

**Comment by OliverCullimore** [comment]
@robbrad great work!

Would it be worth us also looking to set up building and publishing the container to docker hub automatically?

**Comment by robbrad** [comment]
@OliverCullimore yeh 100%!

Not that I know how!

**Comment by OliverCullimore** [comment]
@robbrad I've got an action set up to do it in a few repos such as https://github.com/OliverCullimore/geo-energy-data/blob/main/.github%2Fworkflows%2Fci.yml we can use as reference

You'll need to create a docker hub account if you don't have one already then add secrets with the required details (I'm on mobile so can't easily look at the action for reference to give more detail sorry)

**Comment by robbrad** [comment]
https://github.com/robbrad/UKBinCollectionData/issues/529

**Pull request merged**
