### PR TITLE
Feat: Add Reading Borough Council

### LINKED ISSUE #430: Council request for reading please
### Name of Council

Reading Borough Council

### Example Address/Postcode

RG1 2NU

### Additional Information

https://www.reading.gov.uk/bin-calendar/

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

### PR DESCRIPTION
**Pull request by skelt0**
Closes #430

### CODE REVIEW

**Review by robbrad — APPROVED** [review]

**Comment by skelt0** [comment]
Will re-open with fixed commit messages

**Comment by robbrad** [comment]
@skelt0 can you prefix your commit messages with feat: ?

**Review by robbrad — CHANGES_REQUESTED** [review]
Add prefix of "feat:" to all commit messages- thanks

**Comment by robbrad** [comment]
> Will re-open with fixed commit messages

Thank you

**Comment by robbrad** [comment]
It triggers the release pipeline

**Comment by skelt0** [comment]
> > Will re-open with fixed commit messages
> 
> Thank you

Opened a new PR

**Comment by robbrad** [comment]
https://github.com/robbrad/UKBinCollectionData/actions/runs/7187727612/job/19576354542#step:5:1

Its case sensitive @skelt0 sorry !! 🥹

**Pull request closed without merging**
