### PR TITLE
Added support for Wigan Council

### PR DESCRIPTION
**Pull request by Veasu**
Saw that  #26 was still open even though there was a module for Wigan.

Updated so that the Wigan module should work as expected when given a UPRN and a postcode and added tests for Wigan. If the Wigan module was actually meant to be like that I can revert and add to  a new module but I didn't think that was the case.

### CODE REVIEW

**Review by robbrad — APPROVED** [review]

**Comment by robbrad** [comment]
Thank you @Veasu !

**Comment by dp247** [comment]
@Veasu I don't suppose you have an example command for running this that I can add to the wiki? No worries if not 😄

**Comment by Veasu** [comment]
Sure thing, I was using the command below to run it when I was running it replaced the args with X as looks to be the standard of the current wiki already

`python collect_data.py -u XXXXXXXXXXXX  -p XXXXXX WiganBoroughCouncil https://apps.wigan.gov.uk/MyNeighbourhood/`

**Comment by dp247** [comment]
Awesome, thank you @Veasu!

**Pull request merged**
