### PR TITLE
feat: Add Mid and East Antrim Council

### PR DESCRIPTION
**Pull request by PhilDB-cloud**
feat: Add integration for Mid and East Antrim Borough Council.  I have tested it stand alone and I have run the poetry test script for it and it passes.  Happy for you to make any suggestions and I can follow up or for you to make edits directly.  The website is not particularly easy to scrape.  Doesn't use postcode or uprn so ends up with multiple matches for most addresses searched.

### CODE REVIEW

**Comment by PhilDB-cloud** [comment]
@dp247 Thanks for reviewing.  I have attempted to commit with 'feat:' in.  Please let me know if I need to do it differently.  I'm not very well versed in colaborating in git.

**Comment by robbrad** [comment]
@OliverCullimore : Does the full commit history need every commit message to have the conventional commit prefix?

**Comment by robbrad** [comment]
@PhilDB-cloud in the mean time whil Oliver looks into the previous commit history can you try

`git rebase -i HEAD~25`

Be careful to only edit the commit history of your commit - just add feat: before each and I think you should be good

Dont change the `pick` or the other messages

**Comment by OliverCullimore** [comment]
@robbrad for neatness of the release changelog and for the lint action to pass every commit in the PR is supposed to have a prefix.

But as long as one commit has a correct prefix the automated releases will work so you can ignore the lint action and merge if you like.

**Comment by PhilDB-cloud** [comment]
I was thinking I would just close this pull request and delete the branch and then start again.  It seems less risky and won't take me long to do.  Does that sound ok?

**Comment by dp247** [comment]
Entirely your call, I'm more than happy to merge this as is

**Comment by PhilDB-cloud** [comment]
It seems like it will keep things neater so happy enough to do it.

**Pull request closed without merging**
