### PR TITLE
feat: Add bin colours for North Tyneside

### LINKED ISSUE #631: North Tyneside issues
### Name of Council

North Tyneside

### Issue Information

Installed repo into HACS and configured with appropriate UPRN and postcode correctly formatted with space. Tested with door number as well as door number and street name for brevity. 
Returned results in the integration show inaccurate dates/bin colours when compared with the council's schedule 

image

Output in the entity for grey bin
image
Output in the entity for green bin
image

As you can see there's discrepancy there. 

If there's anything I can do to provide more context or test any further please do let me know. 

Much obliged!

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

### PR DESCRIPTION
**Pull request by psimonkey**
Closes #631

### CODE REVIEW

**Comment by robbrad** [comment]
@psimonkey looks like it's failing the integration test.

See:

https://github.com/robbrad/UKBinCollectionData/actions/runs/10622939636/job/29448304825#step:12:1

You can also test this locally either with the dev container or with the make file. See the contributing.md

Thanks
Rob

**Comment by psimonkey** [comment]
@robbrad The json schema used for the integration tests wasn't expecting the "colour" property on the output.  I've modified that, but I appreciate that's probably quite an impactful change, so might not be an easy merge.

**Comment by robbrad** [comment]
@psimonkey : yeh that's a big impact.

The custom component relies on the consistency.

Does it need to change?

Can the change not be incorporated into the existing schema?

**Comment by robbrad** [comment]
I had a look at this @psimonkey can the colour be part of the type - eg appended strings ?

**Comment by psimonkey** [comment]
HI @robbrad.  I thought the colour functionality was already present in the custom component.  I've just had a look and realised it's not.  Probably best if you reject this PR.  If I get some time I'll have a look at adding colour stuff in all the way through to the sensors, but that might take me a while.

**Comment by robbrad** [comment]
the Way I do it @psimonkey is via the front end 
image

Its not the best but it allows me to set to the colour I like

It would be difficult to dicyper colours from all the councils given the random names for bins they have.

I appreciate your hard work on this - make an easy change might be to append the name of the colour to the type and just return type

**Pull request closed without merging**
