### PR TITLE
#53 Adding junit test report to test run

### PR DESCRIPTION
**Pull request by robbrad**

### CODE REVIEW

**Comment by robbrad** [comment]
@dp247  - https://github.com/robbrad/UKBinCollectionData/runs/7658564452 👀 we now have a visual representation of feature tests passing or failing.

need to see how I can break this down to steps

**Comment by robbrad** [comment]
@dp247 - Even better https://robbrad.github.io/UKBinCollectionData/90/#

**Comment by dp247** [comment]
I do like some nice graphs 👀

**Comment by robbrad** [comment]
https://robbrad.github.io/UKBinCollectionData/ always takes you to the latest feature report

**Pull request merged**
