### PR TITLE
fix: Various council fixes

### PR DESCRIPTION
**Pull request by dp247**
Fixes scrapers for the following councils:
- Basingstoke
- Bath & North East Somerset
- Blackburn
- Malvern Hill
- Swale

Two new dependencies have been added to the TOML as some of them needed custom HTTP handlers to avoid SSL errors.

### CODE REVIEW

**Comment by robbrad** [comment]
Hmm looks like it failed the lint commit 🫣 @dp247 

I need to try this for myself

**Comment by dp247** [comment]
Oh no

**Comment by dp247** [comment]
Should I have a subject and type in every commit message? @OliverCullimore

Maybe that's where I'm going wrong 🤣

**Comment by OliverCullimore** [comment]
@dp247 @robbrad Yes, each one of those commit messages should have "fix:" at the start then your normal message (what it calls subject)

**Comment by OliverCullimore** [comment]
@dp247 There's a few ways you can resolve this:

- Un-commit then recommit your last commit with a message with the "fix:" prefix added to the start (this is what I did for you from my IDE for the last PR)

- Make another change of some kind and commit it with the "fix:" prefix your the commit mesage

- Ignore the lint errors and merge the PR, it just won't create a realease so the fixes will appear the next time a commit with the right prefixes is merged

**Comment by dp247** [comment]
> @dp247 There's a few ways you can resolve this:
> 
> * Un-commit then recommit your last commit with a message with the "fix:" prefix added to the start (this is what I did for you from my IDE for the last PR)
> * Make another change of some kind and commit it with the "fix:" prefix your the commit mesage
> * Ignore the lint errors and merge the PR, it just won't create a realease so the fixes will appear the next time a commit with the right prefixes is merged

Thanks for the tips - I'm gonna fix some more so I'll make sure I preface them correctly 🙏

**Comment by OliverCullimore** [comment]
@dp247 that commit message is looking good 🙌

The lint action will still be erroring because of the previous commits in this PR but that can just be ignored now you've added one with the prefix that will trigger the release 🙂

**Comment by dp247** [comment]
> @dp247 that commit message is looking good 🙌
> 
> The lint action will still be erroring because of the previous commits in this PR but that can just be ignored now you've added one with the prefix that will trigger the release 🙂

Thank god, I was worried I'd have to bring out command line Git to amend them all hehe 🤣

**Review by OliverCullimore — APPROVED** [review]

**Comment by OliverCullimore** [comment]
@dp247 these fixes look good, are you still working on any further changes for this PR or can it be merged now?

**Comment by dp247** [comment]
> @dp247 these fixes look good, are you still working on any further changes for this PR or can it be merged now?

You can merge these for now - I might do a few more today but can always open a new PR

**Pull request merged**
