### PR TITLE
fix: adapt to basingstoke site changes

### PR DESCRIPTION
**Pull request by alexforrow**

### CODE REVIEW

**Comment by robbrad** [comment]
Looks good @alexforrow - but you just need to prefix your commit message with fix: 

eg

`fix: basingstoke adapt to basingstoke site changes`

at the moment its just

`update basingstoke due to site changes`

"Why is this important" - it triggers the release process for the python package on PyPi https://pypi.org/project/uk-bin-collection/

Also if you see an issue in the future please raise an issue for it here https://github.com/robbrad/UKBinCollectionData/issues

Then the comment on the PR can be "Closes Issue No. 123" which will automatically close the issue

**Comment by alexforrow** [comment]
Thanks @robbrad - I've updated commit message, and have also created issue #435 for completeness

**Comment by dp247** [comment]
@alexforrow just an FYI, you can link PRs and issues like [this](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue), so merging a PR automatically closes the issue too :)

**Review by dp247 — APPROVED** [review]

**Comment by robbrad** [comment]
thanks @alexforrow great to see your change has sorted this

image


https://robbrad.github.io/UKBinCollectionData/3.11/1143/#suites/98d3104e051c652961429bf95fa0b5d6/c702fc15318a945c/history

**Pull request merged**
