### PR TITLE
Dotenv changes

### PR DESCRIPTION
**Pull request by dp247**
- Added a .env file to the project root folder, ready to fill in
- Moved .env file loading and `get_usrn` function to `common.py`
- Updated `get_usrn` to check the length of provided API key (if < 1, it throws an exception)
- Added some missing project files for Crawley Borough Council
- Added required change from #159

### CODE REVIEW

**Comment by dp247** [comment]
Paging #198

**Comment by robbrad** [comment]
@dp247 what are your thoughts on making the api part of a parameter you pass in instead?

**Comment by dp247** [comment]
> @dp247 what are your thoughts on making the api part of a parameter you pass in instead?

That would work, for sure. I assumed env after reading something about API keys, so I don't mind changing to something else.

**Comment by dp247** [comment]
Leave it with me, I'll push another branch

**Pull request closed without merging**
