### PR TITLE
This pull request addresses the date parsing issue in `BoltonCouncil.py` caused by a bullet point symbol (⯀) in the date string.

### PR DESCRIPTION
**Pull request by Nextures**
**Changes Made**
- Stripped bullet point symbols from date strings before parsing.

**Testing**
- Successfully tested date parsing with and without bullet point symbols.
- All existing tests pass, and additional tests were added to cover new cases. The script outputs the expected bin collection data.

**Impact**
- No backward compatibility issues expected. This fix should improve the reliability of bin collection date parsing for Bolton Council data.

### CODE REVIEW

**Comment by robbrad** [comment]
__init__.py and poetry. Lock shouldn't be committed

**Comment by robbrad** [comment]
I'll take a look at this tonight

**Comment by Nextures** [comment]
@robbrad I have addressed the feedback regarding unnecessary files. The `__init__.py` and `poetry.lock` files have been removed. Please let me know if everything is ok. 
Thanks

**Comment by robbrad** [comment]
My docker environment was a bit broken and I just managed to fixed it.(dev container)

Let me test this tomorrow morning, on paper looks ok but I want to check something 

Thanks
Rob

**Comment by robbrad** [comment]
@Nextures Thank you for your work on this, However there were too many unecessery changes to imports, testing and error handling that I would not want to introduce.

Meanwhile I have made a commit and changed only whats needed to fix the issue - see:

https://github.com/robbrad/UKBinCollectionData/pull/782/files

Tested: 
image

CICD Tested:
image

Please refer to https://github.com/robbrad/UKBinCollectionData/blob/master/CONTRIBUTING.md#developing for future developing

Thank you

**Pull request closed without merging**
