### PR TITLE
191_fixingbroken_councils

### PR DESCRIPTION
**Pull request by robbrad**
#191

### CODE REVIEW

**Comment by robbrad** [comment]
Fixing first tranche

BasingstokeCouncil
BexleyCouncil
BoltonCouncil
BromleyBoroughCouncil
CalderdaleCouncil
CastlepointDistrictCouncil
CharnwoodBoroughCouncil

**Comment by robbrad** [comment]
@dp247 / @OliverCullimore - when you have finished your Xmas shopping can you merge this ? (dont close the issue as im 7/40 still tracking)

**Review by OliverCullimore — APPROVED** [review]

**Comment by OliverCullimore** [comment]
@robbrad all done with mine already luckily.

Done and left the issue open, just not the PR so reopen if you wanted that left too.

**Comment by LostkingZ** [comment]
@OliverCullimore I can see that I now get asked for a "URL of the remote selenium web driver to use". What do I put here as this is new to me? Do I need to run the Selenium container somehow in Home Assistant? Any help would be much appreciated.

**Pull request merged**
