### PR TITLE
Added Lisburn and Castlereagh City Council

### PR DESCRIPTION
**Pull request by benlyall**
I've added a class to retrieve data for the Lisburn and Castlereagh City Council.

A bit of a weird API, but the interactive flow can be seen by going to https://lisburn.isl-fusion.com/ and entering a postcode, eg. BT26 6LR, and then selecting an address, eg. 32 Ballyworfy Rd.

This class basically replicates that flow, using requests and some parsing of the results. The API seems to return it's payloads as `application/json`, but it includes a `html` key in the JSON object, which I had to parse to match up with a house number. I use that house number of retrieve a unique identifier for an address, which can then be used to look up the bin schedule. The response for the bin schedule includes a `nextCollections` item in the JSON response, so I use that to get the next three weeks of bin collections.

### CODE REVIEW

**Comment by robbrad** [comment]
Thanks @benlyall can you add the associated files to bing in the testing framework. See contributing.md and previous PRs for reference.

**Review by dp247 — COMMENTED** [review]
Looks good to me!

**Comment by dp247** [comment]
> Weirdly, any council that requires the `-s` flag seems to be failing when I run the tests, including the one I'm adding. When I modify the `input.json` to use
> 
> ```
>   "LisburnCastlereaghCityCouncil": {
>     "s": "",
>     "house_number": "97",
>     "postcode": "BT28 1JN",
>     "url": "https://lisburn.isl-fusion.com",
>     "wiki_name": "Lisburn and Castlereagh City Council"
>   }
> ```
> 
> rather than
> 
> ```
>   "LisburnCastlereaghCityCouncil": {
>     "SKIP_GET_URL": "SKIP_GET_URL",
>     "house_number": "97",
>     "postcode": "BT28 1JN",
>     "url": "https://lisburn.isl-fusion.com",
>     "wiki_name": "Lisburn and Castlereagh City Council"
>   }
> ```
> 
> The module I've added passes testing.

Would you mind opening this as an issue, I'd be interested in taking a further look 😊

**Review by dp247 — APPROVED** [review]
Looks good to me!

**Pull request merged**
